### ISSUE TITLE
Branches are being overwritten on being pushed

### ISSUE THREAD

**Issue by ross-spencer** [digipres/policies#5]
It is unclear what is happening yet, but branches are being immediately overwritten when pushed - as @kieranjol points out here, it seems to begin with a failing check on push (it passes in PR state) and then rolls back the commit. A failing check shouldn't result in an incorrect commit being written back into the repository.

NB. while Caylin is listed as the submitter, this is just an automated push. It may also be a clue. 

![image](https://github.com/digipres/policies/assets/1880412/1dd3c606-7a04-488b-b456-8f71c8309421)

TODO:

* Check github actions and remove any "write" behavior in the action if it exists. 
* Look at why Caylin's previous commit is the one being automatically rolled back to.
* Look at the branch protection rules, but check if necessitating passing checks is causing this conflict? 
* Look elsewhere if it's not clear.

**Comment by ross-spencer** [comment]
More information, the workflow result comes through email as follows:

![image](https://github.com/digipres/policies/assets/1880412/b06e15eb-68af-4f5d-9877-c78ee2efdad6)

**Comment by anjackson** [comment]
I think it's working as intended, but is confusing. See https://github.com/digipres/policies/pull/2#issuecomment-1791662732

**Comment by kieranjol** [comment]
Ah! I’d wondered about this earlier. I’ll submit a new PR with changes to the CSV. Perhaps a contributing.md is needed?

**Comment by ross-spencer** [comment]
:facepalm: good spot @anjackson, sorry it has been a minute since working out the mechanics for this repo.
